apiVersion: logicmonitor.com/v1alpha2
kind: CollectorSet
metadata:
  name: {{ include "argus.fullname" . }}
  namespace: {{ template "argus.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}
spec:
  image:
    repository: {{ required "A valid .Values.collector.imageRepository entry is required!" .Values.collector.image.repository }}
    tag: {{ required "A valid .Values.collector.imageTag entry is required!" .Values.collector.image.tag }}
    pullPolicy: {{ required "A valid .Values.collector.imagePullPolicy entry is required!" .Values.collector.image.pullPolicy }}
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: {{ required "A valid .Values.collector.replicas entry is required!" .Values.collector.replicas }}
  size: {{ required "A valid .Values.collector.size entry is required!" .Values.collector.size }}
  clusterName: {{ required "A valid .Values.clusterName entry is required!" .Values.clusterName }}
  {{- if .Values.collector.lm.groupID }}
  groupID: {{ .Values.collector.lm.groupID }}
  {{- end }}
  {{- if .Values.collector.lm.escalationChainID }}
  escalationChainID: {{ .Values.collector.lm.escalationChainID }}
  {{- end }}
  {{- if .Values.collector.version }}
  collectorVersion: {{ .Values.collector.version }}
  {{- end }}
  {{- if .Values.collector.useEA }}
  useEA: {{ .Values.collector.useEA }}
  {{- end }}
  {{- if .Values.collector.proxy.url }}
  proxyURL: {{ .Values.collector.proxy.url }}
  {{- end }}
  {{- if .Values.collector.proxy.user }}
  secretName: {{ include "argus.fullname" . }}-collector
  {{- end }}
{{- if .Values.collector.labels }}
  labels:
{{ toYaml .Values.collector.labels | indent 4 }}
{{- end }}

{{- if .Values.collector.annotations}}
  annotations:
{{ toYaml .Values.collector.annotations| indent 4 }}
{{- end }}

{{- if .Values.collector.statefulsetspec }}
  statefulsetspec:
{{ toYaml .Values.collector.statefulsetspec | indent 4 }}
{{- end }}
