apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus.fullname" . }}
  namespace: {{ template "argus.namespace" . }}
  labels:
    logicmonitor.com/version: v3
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
    {{- include "argus.annotations" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "argus-config" . | fromYaml | toYaml | nindent 4 }}
  filters-config.yaml: |
    filters: {{- toYaml .Values.filters | nindent 6 }}
