apiVersion: v1
kind: Service
metadata:
  name: {{ include "lmutil.fullname" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}
spec:
  ports:
  {{- if .Values.openmetrics }}
    - port: {{ .Values.openmetrics.port }}
      targetPort: {{ .Values.openmetrics.port }}
      name: openmetrics
  {{- else }}
    - port: 2112
      targetPort: 2112
      name: openmetrics
  {{- end }}
  {{- if .Values.enableProfiling }}
    - port: 8081
      targetPort: 8081
      name: profiling
  {{- end }}
  selector:
    {{- include "lmutil.selectorLabels" . | nindent 4 }}
