---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argus.serviceAccountName" . }}-collector
  namespace: {{ template "argus.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}