apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  {{- if .Values.openmetrics }}
    - port: {{ .Values.openmetrics.port }}
      targetPort: {{ .Values.openmetrics.port }}
      name: openmetrics
  {{- else }}
    - port: 2112
      targetPort: 2112
      name: openmetrics
  {{- end }}
  {{- if .Values.enableProfiling }}
    - port: 8081
      targetPort: 8081
      name: profiling
  {{- end }}
  selector:
    app: {{ .Release.Name }}
