{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lmutil.serviceAccountName" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}
imagePullSecrets:
  {{- include "lmutil.imagePullSecrets" . | nindent 2 }}
{{ end }}