{{ $saUsers := list (printf "%s:%s" (include "lmutil.release.namespace" .) (include "collectorset-controller.serviceAccountName" .)) }}
{{ $params := list . "lm-nonroot-v2-collectorset-controller" $saUsers }}
{{ include "lmutil.openshift-scc-nonroot-v2" $params }}
---
{{ $users := list (printf "%s:%s-collector" (include "lmutil.release.namespace" .) (include "collectorset-controller.serviceAccountName" .)) }}
{{ $caps := list "NET_RAW" "SETFCAP" }}
{{ $input := list . "lm-anyuid-collector" $users $caps }}
{{ include "lmutil.openshift-scc-anyuid" $input }}