{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "collectorset-controller.serviceAccountName" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "collectorset-controller.labels" . | nindent 4}}
  annotations:
    {{- include "collectorset-controller.annotations" . | nindent 4}}
imagePullSecrets:
  {{- include "lmutil.imagePullSecrets" . | nindent 2 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "collectorset-controller.serviceAccountName" . }}-collector
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "collectorset-controller.labels" . | nindent 4}}
  annotations:
    {{- include "collectorset-controller.annotations" . | nindent 4}}
imagePullSecrets:
  {{- include "lmutil.imagePullSecrets" . | nindent 2 }}
{{ end }}