{{- if .Values.ingress.enabled }}
{{- $ingressSupportsPathType := eq (include "ingress.supportsPathType" .) "true" -}}
{{- $isIngressAPIStable :=  eq (include "ingress.isStable" .) "true" -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "lmutil.fullname" . }}-grpc
  labels:
    {{ include "lmotel.labels" . | nindent 4 }}
  {{- if .Values.ingress.customLabels }}
  {{- with .Values.ingress.customLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    {{ include "lmotel.annotations" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  {{- range $key,$value := .Values.ingress.annotations }}  
    {{ $key }}: {{ $value | quote }} 
  {{- end }}     
  {{- end }}

  {{- if .Values.ingress.grpc.annotations }}
  {{- range $key,$value := .Values.ingress.grpc.annotations }}  
    {{ $key }}: {{ $value | quote }} 
  {{- end }}     
  {{- end }}

spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{.Values.ingress.host}}
      {{- with .Values.service }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $isIngressAPIStable }}
              service:
                name: {{ .name }}
                port:
                  number: {{ .ports.grpc }}
              {{- else }}
              serviceName: {{ .name }}
              servicePort: {{ .ports.grpc }}
              {{- end }}
      {{- end }}
  tls:
    - hosts:
        - {{.Values.ingress.host}}
    {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . }}
    {{- end }}
{{- end }}
