{{- if .Values.ingress.enabled }}
{{- $ingressSupportsPathType := eq (include "ingress.supportsPathType" .) "true" -}}
{{- $isIngressAPIStable :=  eq (include "ingress.isStable" .) "true" -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "lmutil.fullname" . }}-http
  labels:
    {{ include "lmotel.labels" . | nindent 4 }}
  {{- if .Values.ingress.customLabels }}
  {{- with .Values.ingress.customLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    {{ include "lmotel.annotations" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  {{- range $key,$value := .Values.ingress.annotations }}  
    {{ $key }}: {{ $value | quote }} 
  {{- end }}     
  {{- end }}

  {{- if .Values.ingress.http.annotations }}
  {{- range $key,$value := .Values.ingress.http.annotations }}  
    {{ $key }}: {{ $value | quote }} 
  {{- end }}     
  {{- end }}

spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{.Values.ingress.host}}
      {{- with .Values.service }}
      http:
        paths:
          - path: /rest/api/(.*)
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $isIngressAPIStable }}
              service:
                name: {{.name}}
                port:
                  number: {{.ports.http}}
              {{- else }}
              serviceName: {{ .name }}
              servicePort: {{ .ports.http}}
              {{- end }}
          - path: /health
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $isIngressAPIStable }}
              service:
                name: {{.name}}
                port:
                  number: {{.ports.healthcheck }}
              {{- else }}
              serviceName: {{ .name }}
              servicePort: {{ .ports.healthcheck }}
              {{- end }}
      {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . }}
      {{- end }}
{{- end }}
