apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lmutil.fullname" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "lmotel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.lm.bearer_token}}
  lm_bearer_token: {{ .Values.lm.bearer_token | b64enc }}
  {{ end }}
  {{- if or (.Values.lm.access_key) (.Values.global.accessID)}}
  lm_access_key: {{ if .Values.lm.access_key }} {{ .Values.lm.access_key | b64enc }} {{ else }} {{ required "A valid .Values.lm.access_key or .Values.global.accessKey entry is required!" .Values.global.accessKey | b64enc }} {{ end }}
  {{ end }}