apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "lmotel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $key, $val := .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $val }}
      targetPort: {{ $val }}
{{- end }}
  selector:
    {{ include "lmutil.selectorLabels" . | nindent 6 }}