{{- if eq .Values.logs.enable false}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lmutil.fullname" . }}
  namespace: {{ include "lmutil.release.namespace" . }}
  labels:
    {{ include "lmotel.labels" . | nindent 4 }}
  annotations:
    {{ include "lmotel.annotations" . | nindent 4 }}
spec:
# servicename used only in case of statefulset
  serviceName: {{ .Values.service.name }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{ include "lmutil.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "lmotel.labels" . | nindent 8 }}
      annotations:
        {{ include "lmotel.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: lmotel
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "lmotel-image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{ with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{- if .Values.arguments}}
          args:  
            {{ range .Values.arguments }}
              - {{ . }}
            {{ end }}
          {{- end }}
          env:
            - name: LOGICMONITOR_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_account
            - name: LOGICMONITOR_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_bearer_token
                  optional: true
            - name: LOGICMONITOR_ACCESS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_access_id
                  optional: true
            - name: LOGICMONITOR_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_access_key
                  optional: true                
            - name: LOGICMONITOR_OTEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_otel_name                  
            - name: LOGICMONITOR_OTEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lmutil.fullname" . }}
                  key: lm_version
                  optional: true
            - name: LOGICMONITOR_OTEL_NAMESPACE
              value: {{ include "lmutil.release.namespace" . }}
          {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.external_config.lmconfig}}
          args: 
              - --config
              - lmconfig.yaml
              {{- if .Values.arguments}}  
              {{ range .Values.arguments }}
              - {{ . }}
              {{ end }}
              {{- end }}
          volumeMounts:
            - name: lmotel-conf
              mountPath: lmconfig.yaml
              subPath: lmconfig.yaml
          {{- end }}
      volumes:
      {{- if .Values.external_config.lmconfig }}
        - name: lmotel-conf
          configMap:
            name: {{ include "lmutil.fullname" . }}
            items:
              - key: lmconfig.yaml
                path: lmconfig.yaml
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}