apiVersion: v1
kind: Service
metadata:
  name: {{ template "releasemanager.name" . }}
  labels:
    chart: {{ template "releasemanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "releasemanager.name" . }}
  ports:
  - name: app
    port: 8080
