apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lm-container.fullname" . }}
  namespace: {{ template "lm-container.namespace" . }}
  labels:
    logicmonitor.com/version: v3
    {{- include "lm-container.labels" . | nindent 4 }}
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
    {{- include "lm-container.annotations" . | nindent 4 }}
data:
  debug-info: |
    capabilities:
      {{- toYaml .Capabilities | nindent 6 }}
    release:
      {{- toYaml .Release | nindent 6 }}
    values:
      {{- toYaml .Values | nindent 6 }}
