name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        # do not use default github token, as it does not raise release created event for post release github actions
        env:
          CR_TOKEN: "${{ secrets.CHART_RELEASE_TOKEN }}"

      - name: setup yq
        run: sudo snap install yq

      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: gh-pages
          ref: gh-pages
      - name: Generate Version Skew Matrix
        run: |
          yq gh-pages/index.yaml -o json > tmp.json
          touch out.md
          printf "# VERSION SKEW MATRIX" >> out.md
          printf "\n## Argus Releases\n" >> out.md
          echo "| name | version | appVersion | dependencies |" >> out.md
          echo "| :---- | :---- | :---- | :---- |" >> out.md
          cat tmp.json | jq -jr '(.entries."argus"[] | "| ", .name, " | [", .version, "](https://github.com/logicmonitor/helm-charts/releases/tag/argus-", .version , ") | ", if .appVersion != null then ("[", .appVersion, "](https://hub.docker.com/r/logicmonitor/argus/tags?page=1&name=", .appVersion, ")") else empty end, " | " as $out | " | <ul> ", (.dependencies[]? | "<li>", .name, "@" ,.version, " " , .repository,  "</li>" ), " </ul> | \n")' >> out.md
          printf "\n## Collectorset Controller Releases\n" >> out.md
          echo "| name | version | appVersion | dependencies |" >> out.md
          echo "| :---- | :---- | :---- | :---- |" >> out.md
          cat tmp.json | jq -jr '(.entries."collectorset-controller"[] | "| ", .name, " | [", .version, "](https://github.com/logicmonitor/helm-charts/releases/tag/collectorset-controller-", .version , ") | ", if .appVersion != null then ("[", .appVersion, "](https://hub.docker.com/r/logicmonitor/collectorset-controller/tags?page=1&name=", .appVersion, ")") else empty end, " | " as $out | " | <ul> ", (.dependencies[]? | "<li>", .name, "@" ,.version, " " , .repository,  "</li>" ), " </ul> | \n")' >> out.md
          printf "\n## LM Container Releases\n" >> out.md
          echo "| name | version | appVersion | dependencies |" >> out.md
          echo "| :---- | :---- | :---- | :---- |" >> out.md
          cat tmp.json | jq -jr '(.entries."lm-container"[] | "| ", .name, " | [", .version, "](https://github.com/logicmonitor/helm-charts/releases/tag/lm-container-", .version , ") | ", if .appVersion != null then ("[", .appVersion, "](https://hub.docker.com/r/logicmonitor/lm-container/tags?page=1&name=", .appVersion, ")") else empty end, " | " as $out | " | <ul> ", (.dependencies[]? | "<li>", .name, "@" ,.version, " " , .repository,  "</li>" ), " </ul> | \n")' >> out.md
          cp out.md gh-pages/VERSION-SKEW-MATRIX.md
      - name: Push Version Skew Matrix
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          repository: gh-pages
          commit_message: "docs(readme): update version skew"
          file_pattern: "VERSION-SKEW-MATRIX.md"
